---
- name: validate Homebrew
  user: ansible
  hosts: all
  gather_facts: true
  become: true
  roles:
    - ansible-homebrew
  task:
    - command: "/home/{{ ansible_user }}/.linuxbrew/bin/brew"
      become: false
